#!/usr/bin/env bash

SRC_PATH="${HOME}/.crashplanremote/"

UI_PROP_PATH="/Applications/CrashPlan.app/Contents/Resources/Java/conf/"
UI_INFO_PATH="/Library/Application Support/CrashPlan/"

UI_PROP="${UI_PROP_PATH}ui.properties"
UI_PROP_DISKSTATION="${SRC_PATH}ui.properties.diskstation"
UI_PROP_LOCAL="${SRC_PATH}ui.properties.local"
UI_INFO="${UI_INFO_PATH}.ui_info"
UI_INFO_DISKSTATION="${SRC_PATH}ui_info.diskstation"
UI_INFO_LOCAL="${SRC_PATH}ui_info.local"

function help {
    echo -e "Usage: $SCRIPT [-r]"
    echo -e ""
    echo -e " Copy the crash plan configuration files from the"
    echo -e "  ~/.crashplanremote directory. Run the currently"
    echo -e " installed version of crash plan. After the crash"
    echo -e " plan app exits, copy back the local config files"
    echo -e ""
    echo -e " -r will refresh the cached local crash plan config files"
    echo -e "    by copying them from their local location."
    exit -1
}

sudo cp -v "${UI_PROP_DISKSTATION}" "${UI_PROP}"
sudo cp -v "${UI_INFO_DISKSTATION}" "${UI_INFO}"

echo "Open the CrashPlan app and wait..."
open -Wa CrashPlan

echo "Copy local configuation files..."
sudo cp -v "${UI_PROP_LOCAL}" "${UI_PROP}"
sudo cp -v "${UI_INFO_LOCAL}" "${UI_INFO}"

